# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jnmh6V1mXB16ip32ntDqLLZDcmPPoKcK
"""

import streamlit as st
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import joblib

# Load the trained model
model = joblib.load('flight_fare_prediction_model.pkl')

def predict_price(journey_day, journey_month, dep_hour, dep_minute):
    # Predict the flight fare using the trained model
    prediction = model.predict([[journey_day, journey_month, dep_hour, dep_minute]])
    return round(prediction[0], 2)

def main():
    st.title('Flight Price Prediction')

    dep_time = st.date_input('Departure Time')
    arrival_time = st.date_input('Arrival Time')
    stops = st.number_input('Number of Stops', min_value=0, max_value=10, value=0)
    airline = st.selectbox('Select Airline', ['Air India', 'GoAir', 'IndiGo', 'Jet Airways', 'Multiple carriers', 'SpiceJet', 'Vistara', 'Other'])
    source = st.selectbox('Select Source', ['Chennai', 'Kolkata', 'Mumbai', 'Delhi'])
    destination = st.selectbox('Select Destination', ['Cochin', 'Delhi', 'Hyderabad', 'Kolkata'])

    # Convert dep_time to datetime.datetime object
    dep_datetime = pd.to_datetime(dep_time)
    journey_day = dep_datetime.day
    journey_month = dep_datetime.month
    dep_hour = dep_datetime.hour
    dep_minute = dep_datetime.minute

    if st.button('Predict'):
        # Call the predict_price function to get the prediction
        price = predict_price(journey_day, journey_month, dep_hour, dep_minute)
        st.write(f'Your flight price prediction is Rs. {price}')

if __name__ == '__main__':
    main()